Repository 4-teamGPT/teamGPT, pull requests merged in 2025-06, with the labels that each got.

#2 Feature/login
  src/assets/img/Rectangle 47.png
  src/assets/img/dog-face.svg
  src/assets/img/dog-smile.svg
  src/assets/img/dog-with-paper.svg
  src/assets/img/lee.jpg
  src/assets/img/logo.png
  src/assets/img/newJeans.jpg
  src/assets/img/son.jpeg
  src/assets/img/son2.jpg
  src/components/NewsComponents/NewsComponent1.vue
  src/components/NewsComponents/NewsComponent2.vue
  src/components/NewsComponents/NewsComponent3.vue
  src/components/NewsComponents/NewsComponent4.vue
  src/components/icon/sportBtn.vue
  src/router/index.js
  src/views/LoginView.vue
  src/views/SignUpView.vue
Labels: ✨ feature, 🎨 style

#3 ✨ Feat: 커뮤니티 페이지 퍼블리싱 및 ProfileCard 컴포넌트 생성
  package-lock.json
  package.json
  src/App.vue
  src/components/common/ProfileCard.vue
  src/components/community/CommunityModal.vue
  src/components/community/CommunityPost.vue
  src/components/community/CommunityPostDetail.vue
  src/main.js
  src/router/index.js
  src/views/community/CommunityDetailView.vue
  src/views/community/CommunityListView.vue
Labels: ✨ feature, 🎨 style

#5 ✨ Feat: NewsList, News detail page 퍼블리싱 작업/ font 설정
  index.html
  jsconfig.json
  package-lock.json
  package.json
  src/App.vue
  src/api/fetchNews.js
  src/api/getSupabaseNews.js
  src/api/saveNews.js
  src/assets/main.css
  src/components/NewsComponents/NewsComponent2.vue
  src/components/NewsComponents/NewsComponent9.vue
  src/components/common/MenuSidebar.vue
  src/layout/NewsLayout.vue
  src/main.js
  src/router/index.js
  src/stores/newsData.js
  src/views/NewsDetailView.vue
  src/views/NewsListView.vue
  vite.config.js
Labels: ✨ feature, 🎨 style

#6 ✨ Feat: 관심사 선택, 최고 관심사 선택 페이지 추가
  package-lock.json
  package.json
  src/App.vue
  src/assets/fonts/BagelFatOne.woff
  src/assets/fonts/BagelFatOne.woff2
  src/assets/icons/alert.svg
  src/assets/icons/headerLogoImg.svg
  src/assets/icons/modeToggle.svg
  src/assets/icons/newspaperDog.svg
  src/assets/icons/searchIcon.svg
  src/assets/main.css
  src/assets/root.css
  src/components/common/ButtonVue.vue
  src/components/common/FooterVue.vue
  src/components/common/HeaderView.vue
  src/layout/DefaultLayout.vue
  src/main.js
  src/router/index.js
  src/stores/interestStore.js
  src/views/ChooseInterest.vue
  src/views/FavoriteInterest.vue
  src/views/HomeView.vue
  vite.config.js
Labels: ✨ feature

#7 ✨ Feat: 헤더 컴포넌트 퍼블리싱, 로고 폰트 추가
  package-lock.json
  package.json
  src/App.vue
  src/assets/fonts/BagelFatOne.woff
  src/assets/fonts/BagelFatOne.woff2
  src/assets/icons/alert.svg
  src/assets/icons/headerLogoImg.svg
  src/assets/icons/modeToggle.svg
  src/assets/icons/newspaperDog.svg
  src/assets/icons/searchIcon.svg
  src/assets/main.css
  src/assets/root.css
  src/components/common/ButtonView.vue
  src/components/common/FooterView.vue
  src/components/common/HeaderView.vue
  src/main.js
  src/router/index.js
  src/views/HomeView.vue
  vite.config.js
Labels: ✨ feature, 🎨 style

#9 ✨Feat: Profile edit 화면 및 profile news 화면 생성, 라우터 연결
  src/assets/img/blackBtn.svg
  src/assets/img/smallGrayBtn.svg
  src/assets/img/smallVioletBtn.svg
  src/assets/img/son.jpeg
  src/components/icon/blackBtn.vue
  src/components/icon/smallGrayBtn.vue
  src/components/icon/smallVioletBtn.vue
  src/components/icon/smallWhiteBtn.vue
  src/components/profile/SleepDog.vue
  src/router/index.js
  src/views/ProfileEditView.vue
  src/views/ProfileNewsView.vue
Labels: ✨ feature, 🎨 style

#10 Feature/login
  src/assets/img/logo.png
  src/assets/img/logo.svg
  src/views/LoginView.vue
  src/views/SignUpView.vue
Labels: ✨ feature, 🎨 style

#11 💄 Style: 뉴스 상세페이지 수정
  src/assets/fonts/PretendardVariable.woff2
  src/assets/icons/Chevron--left.svg
  src/assets/img/logo_newsdocs.png
  src/assets/img/news_image/dummy1.png
  src/assets/img/news_image/dummy2.png
  src/assets/img/news_image/dummy3.png
  src/assets/main.css
  src/components/NewsComponents/NewsComponent1.vue
  src/components/NewsComponents/NewsComponent2.vue
  src/components/NewsComponents/NewsComponent3.vue
  src/components/common/BackButton.vue
  src/components/common/HeaderView.vue
  src/components/common/MenuSidebar.vue
  src/layout/DefaultLayout.vue
  src/layout/NewsLayout.vue
  src/router/index.js
  src/views/NewsDetailView.vue
  src/views/NewsListView.vue
  src/views/newsDetail/CommunityRecommend.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
  src/views/newsDetail/NewsRecommend.vue
Labels: 🎨 style

#12 💄 Style: 커뮤니티 상세페이지, 게시글 작성 모달 퍼블리싱
  src/assets/icons/Add-comment.svg
  src/assets/icons/Chevron--down.svg
  src/assets/icons/Edit.svg
  src/assets/icons/Image.svg
  src/assets/icons/Trash-can.svg
  src/assets/icons/backButton.svg
  src/assets/icons/commentModal.svg
  src/assets/icons/commentModalHover.svg
  src/assets/icons/communityDropdown/celeb.svg
  src/assets/icons/communityDropdown/culture.svg
  src/assets/icons/communityDropdown/economy.svg
  src/assets/icons/communityDropdown/global.svg
  src/assets/icons/communityDropdown/politics.svg
  src/assets/icons/communityDropdown/social.svg
  src/assets/icons/communityDropdown/sports.svg
  src/assets/icons/imageAdd.svg
  src/assets/img/Chat.svg
  src/assets/img/ChatImg.svg
  src/assets/img/communityDetailImg.svg
  src/assets/img/communityPostImg.svg
  src/assets/img/communitywriterProfile.svg
  src/assets/img/profileCardDog.svg
  src/components/common/ProfileCard.vue
  src/components/community/CommunityModal.vue
  src/components/community/CommunityPost.vue
  src/components/community/CommunityPostDetail.vue
  src/main.js
  src/stores/newPostStore.js
  src/views/PostCreateView.vue
  src/views/community/CommunityDetailView.vue
  src/views/community/CommunityListView.vue
Labels: 🎨 style

#13 ✨ feat : 회원가입 로직 및 superbase api 연결
  src/views/LoginView.vue
  src/views/SignUpView.vue
Labels: 🛠️ api, ✨ feature, 🎨 style

#16 ✨ Feat: 다크모드 적용 버튼 추가
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/main.css
  src/components/NewsComponents/NewsComponent3.vue
  src/components/common/HeaderView.vue
  src/stores/useDarkmode.js
  tailwind.config.js
Labels: ✨ feature, 🎨 style

#14 💄 Style: 프로필 페이지 스타일 수정
  src/assets/img/profileDog.svg
  src/components/NewsComponents/NewsComponent8.vue
  src/components/community/CommunityPost.vue
  src/components/icon/profileDog.vue
  src/components/icon/sleepDog.vue
  src/components/icon/violetBtn.vue
  src/components/profile/SleepDog.vue
  src/router/index.js
  src/views/ProfileEditView.vue
  src/views/ProfileNewsView.vue
  src/views/ProfileView.vue
  src/views/community/CommunityListView.vue
  src/views/profile/ProfileEditView.vue
  src/views/profile/ProfileNewsView.vue
  src/views/profile/ProfileView.vue
  src/views/profile/ProfileWriteView.vue
Labels: ♻️ refactor, ✨ feature, 🎨 style

#17 💄 Style: 뉴스 상세 페이지 다크모드 적용
  src/assets/img/dark_logo.png
  src/assets/main.css
  src/components/common/BackButton.vue
  src/components/common/HeaderView.vue
  src/views/newsDetail/CommunityRecommend.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
  src/views/newsDetail/NewsRecommend.vue
Labels: 🎨 style

#23 💄 Style: 커뮤니티 다크모드 적용
  src/assets/main.css
  src/components/common/ProfileCard.vue
  src/components/community/CommunityComment.vue
  src/components/community/CommunityCommentModal.vue
  src/components/community/CommunityModal.vue
  src/components/community/CommunityMyComment.vue
  src/components/community/CommunityPost.vue
  src/components/community/CommunityPostDetail.vue
  src/views/community/CommunityDetailView.vue
  src/views/community/CommunityListView.vue
Labels: 🎨 style

#24 💄 Style: 모든소식 페이지 퍼블리싱
  src/components/NewsComponents/NewsComponent1.vue
  src/components/NewsComponents/NewsComponent3.vue
  src/components/NewsComponents/SlideNewsComponent.vue
  src/layout/NewsLayout.vue
  src/router/index.js
  src/views/AboutView.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
Labels: 🎨 style

#27 Feature/login
  package-lock.json
  package.json
  src/App.vue
  src/assets/main.css
  src/assets/toast-custom.css
  src/main.js
  src/views/LoginView.vue
  src/views/SignUpView.vue
Labels: 🛠️ api, ✨ feature, 🎨 style

#32 Feature/interest
  src/App.vue
  src/api/auth.js
  src/router/index.js
  src/stores/authStore.js
  src/views/ChooseInterest.vue
  src/views/FavoriteInterest.vue
  src/views/SignUpView.vue
Labels: 🛠️ api, ✨ feature

#33 Feature/login
  src/App.vue
  src/composables/useGoogleAuth.js
  src/views/LoginView.vue
Labels: 🛠️ api, ✨ feature

#34 ✨ Feat: 프로필 사진 변경 기능 추가 및 타인의 프로필 확인 기능 추가
  src/api/fetchInterest.js
  src/api/fetchUserByNickname.js
  src/api/updateProfileImg.js
  src/components/NewsComponents/NewsComponent8.vue
  src/components/community/CommunityPost.vue
  src/components/icon/profileDog.vue
  src/components/profile/SleepDog.vue
  src/layout/DefaultLayout.vue
  src/router/index.js
  src/views/profile/ProfileNewsView.vue
  src/views/profile/ProfileView.vue
  src/views/profile/ProfileWriteView.vue
Labels: ♻️ refactor, ✨ feature

#36 ✨ 404 라우트 추가
  src/assets/img/dog-notfound.png
  src/router/index.js
  src/views/NotFound.vue
Labels: ✨ feature, 🎨 style

#37 🚑 hotfix : pinia 연동 동기화
  src/main.js
Labels: 🔥 hotfix

#38 ✨ Feat: 뉴스 컴포넌트 요약기능 추가
  package-lock.json
  package.json
  public/tailwind.config.js
  src/api/fetchOpenAi.js
  src/components/NewsComponents/NewsComponent1.vue
  src/stores/summaryNews.js
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
Labels: 🛠️ api, ✨ feature, 🎨 style

#45 💄 Style: 요약화면 로딩 애니메이션 추가
  package-lock.json
  package.json
  src/assets/img/son.jpeg
  src/components/NewsComponents/NewsComponent1.vue
  src/views/MyInterest.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
Labels: 🐛 fix, 🎨 style

#46 ✨ 커뮤니티 좋아요, 댓글 추가, 프로필 카드 수정
  src/api/community/comment.js
  src/api/community/fetchCategory.js
  src/api/community/fetchPostDetail.js
  src/api/community/like.js
  src/api/community/post.js
  src/api/fetchUser.js
  src/api/getCurrentUser.js
  src/assets/icons/Add-comment.svg
  src/assets/icons/Chevron--down.svg
  src/assets/icons/Edit.svg
  src/assets/icons/Image.svg
  src/assets/icons/Trash-can.svg
  src/assets/icons/backButton.svg
  src/assets/icons/commentModal.svg
  src/assets/icons/commentModalHover.svg
  src/assets/icons/imageAdd.svg
  src/assets/img/communityImg/newsdog4.svg
  src/assets/img/communityImg/profileDefault.svg
  src/components/common/ProfileCard.vue
  src/components/community/CommunityComment.vue
  src/components/community/CommunityCommentModal.vue
  src/components/community/CommunityModal.vue
  src/components/community/CommunityMyComment.vue
  src/components/community/CommunityPost.vue
  src/components/community/CommunityPostDetail.vue
  src/composables/userRelativeTime.js
  src/views/PostCreateView.vue
  src/views/community/CommunityDetailView.vue
  src/views/community/CommunityListView.vue
Labels: 🛠️ api, ✨ feature, 🎨 style

#48 Feature/login
  package-lock.json
  package.json
  src/components/UserForm.vue
  src/utils/userSchema.js
  src/views/LoginView.vue
  src/views/NotFound.vue
  src/views/SignUpView.vue
Labels: ♻️ refactor, 🐛 fix

#51 Feature/header
  jsconfig.json
  src/assets/icons/notification.svg
  src/assets/icons/profile-white.svg
  src/assets/icons/profile.svg
  src/assets/icons/toDarkMode.svg
  src/assets/icons/toLightMode.svg
  src/assets/img/blackBtn.svg
  src/assets/img/dark_logo.png
  src/assets/img/dog-notfound-v2.png
  src/assets/img/dog-notfound.png
  src/assets/img/dog-trans.svg
  src/assets/img/logoDog.svg
  src/assets/img/logo_newsdocs.png
  src/assets/img/profileEditBtn.svg
  src/assets/img/smallGrayBtn.svg
  src/assets/img/smallVioletBtn.svg
  src/assets/img/violetBtn.svg
  src/components/common/DarkModeButton.vue
  src/components/common/DropBox.vue
  src/components/common/FooterView.vue
  src/components/common/HeaderBasic.vue
  src/components/common/HeaderView.vue
  src/views/LoginView.vue
  src/views/NotFound.vue
  src/views/SignUpView.vue
Labels: ✨ feature, 🎨 style

#52 ✨ Feat: 카테고리에 맞는 커뮤니티 게시글 추천
  package-lock.json
  src/api/fetchNews.js
  src/api/updateLikeNewsCount.js
  src/api/updateViewCount.js
  src/assets/img/news_image/dummy1.png
  src/assets/img/news_image/dummy2.png
  src/assets/img/news_image/dummy3.png
  src/assets/img/run_dog.png
  src/assets/root.css
  src/components/NewsComponents/NewsComponent1.vue
  src/components/NewsComponents/NewsComponentCommunity.vue
  src/views/MyInterest.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
  src/views/newsDetail/NewsRecommend.vue
  src/views/profile/ProfileNewsView.vue
  src/views/profile/ProfileView.vue
Labels: 🛠️ api, ✨ feature, 🎨 style

#56 ✨ Feat: 관심사 페이지 hotDocs 렌더링
  src/api/hotDocs.js
  src/components/NewsComponents/HotDocsComponent.vue
  src/components/NewsComponents/NewsComponent10.vue
  src/components/NewsComponents/NewsComponent5.vue
  src/components/NewsComponents/NewsComponent6.vue
  src/components/NewsComponents/NewsComponent7.vue
  src/components/NewsComponents/NewsComponent8.vue
  src/components/NewsComponents/NewsComponent9.vue
  src/components/NewsComponents/NewsComponentCommunity.vue
  src/components/NewsComponents/section/FavoriteSection.vue
  src/components/NewsComponents/section/FifthSection.vue
  src/components/NewsComponents/section/FourthSection.vue
  src/components/NewsComponents/section/SecondSection.vue
  src/components/NewsComponents/section/SixthSection.vue
  src/components/NewsComponents/section/ThirdSection.vue
  src/router/index.js
  src/views/MyInterest.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
Labels: 🛠️ api, ✨ feature, 🎨 style

#63 🚨 Fix: 알림 오류 해결
  src/App.vue
  src/api/community/realTimeAlarm.js
  src/components/common/DropBox.vue
  src/components/common/HeaderView.vue
  src/components/community/CommunityAlarm.vue
  src/components/community/CommunityPostDetail.vue
  src/components/community/CommunityPostModal.vue
  src/stores/useNotiStore.js
Labels: 🐛 fix, 🎨 style

#64 Feature/server
  package-lock.json
  package.json
  src/components/NewsComponents/NewsComponent8.vue
  src/composables/fetchNewsDesciption.js
  src/composables/newsCache.js
  src/stores/newsStore.js
  src/views/MyInterest.vue
Labels: 🛠️ api, ✨ feature

#65 ✨ Feat: 카테고리별 뉴스 접근 가능
  package-lock.json
  src/components/NewsComponents/NewsComponent4.vue
  src/components/NewsComponents/NewsComponent5.vue
  src/components/NewsComponents/skeleton/NewsComponentSkel/SNCSkel.vue
  src/components/NewsComponents/txt
  src/composables/tanstackHooks/useNewsData.js
  src/composables/tanstackHooks/useRandomNews.js
  src/composables/tanstackHooks/useShortDocs.js
  src/layout/NewsLayout.vue
  src/main.js
  src/router/index.js
  src/stores/interestStore.js
  src/views/newsDetail/CategoryHeader.vue
  src/views/newsDetail/CategoryView.vue
  src/views/newsDetail/NewsListView.vue
Labels: 🛠️ api, ✨ feature

#66 ✨ feat : sb에 저장할 때, 카테고리 맵핑해서 저장
  src/composables/newsCache.js
  src/composables/useCategoryMap.js
  src/composables/useInterestMap.js
  src/composables/useNewsActions.js
  src/views/ChooseInterest.vue
Labels: ✨ feature

#68 ✨ Feat: 게시글 수정/삭제 , 알림 오류 해결
  package-lock.json
  src/App.vue
  src/api/community/notification.js
  src/api/community/post.js
  src/api/community/realTimeAlarm.js
  src/assets/icons/communityDropdown/etc.svg
  src/components/common/HeaderView.vue
  src/components/community/CommunityAlarm.vue
  src/components/community/CommunityAlarmBlock.vue
  src/components/community/CommunityCommentModal.vue
  src/components/community/CommunityModal.vue
  src/components/community/CommunityPostDetail.vue
  src/components/community/CommunityPostModal.vue
  src/components/community/skeleton/CommunityALarmSkel.vue
  src/stores/useNotiStore.js
  src/views/community/CommunityDetailView.vue
  src/views/community/CommunityListView.vue
Labels: ✨ feature, 🐛 fix

#71 🚨 Fix: 알림 오류 수정, 다크모드 프로필카드 수정
  src/App.vue
  src/api/community/notification.js
  src/components/common/ProfileCard.vue
  src/composables/useSetupNoti.js
  src/views/LoginView.vue
  src/views/community/CommunityListView.vue
  src/views/profile/ProfileEditView.vue
Labels: 🐛 fix, 🎨 style

#70 🔨 Refactor: api 분기 작업
  src/api/fetchOpenAi.js
  src/assets/fonts/BagelFatOne.woff
  src/assets/fonts/BagelFatOne.woff2
  src/assets/main.css
  src/components/NewsComponents/NewsComponent0.vue
  src/components/NewsComponents/NewsComponent8.vue
  src/components/NewsComponents/NewsComponent9.vue
  src/components/common/HeaderView.vue
  src/composables/newsCache.js
  src/composables/useNewsActions.js
  src/composables/useSummary.js
  src/composables/useTyping.js
  src/main.js
  src/router/index.js
  src/stores/summaryNews.js
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsListView.vue
Labels: ♻️ refactor, 🛠️ api

#77 ✨ Feat: 유저 관심사 받아와서 렌더링, 모든소식 전체 카테고리
  src/components/NewsComponents/NewsComponent0.vue
  src/composables/newsCache.js
  src/composables/useCategoryMap.js
  src/views/MyInterest.vue
  src/views/myinterestScript.js
  src/views/newsDetail/CategoryView.vue
  src/views/newsDetail/NewsListView.vue
Labels: ♻️ refactor, 🛠️ api, 🐛 fix

#78 🔨 Refactor: api 분리, 렌더링작업 마무리
  src/components/NewsComponents/HotDocsComponent.vue
  src/components/NewsComponents/NewsComponent0.vue
  src/components/NewsComponents/NewsComponent10.vue
  src/components/NewsComponents/NewsComponent5.vue
  src/components/NewsComponents/NewsComponent8.vue
  src/components/NewsComponents/NewsComponent9.vue
  src/components/NewsComponents/SlideNewsComponent.vue
  src/components/NewsComponents/section/FavoriteSection.vue
  src/components/NewsComponents/section/SecondSection.vue
  src/components/NewsComponents/section/ThirdSection.vue
  src/components/NewsComponents/skeleton/FavoriteSectionSkel.vue
  src/components/NewsComponents/skeleton/SecondSectionSkel.vue
  src/components/common/HeaderView.vue
  src/composables/newsCache.js
  src/composables/useSummary.js
  src/stores/interestStore.js
  src/views/MyInterest.vue
Labels: ♻️ refactor, 🛠️ api, 🎨 style

#76 💄 Style: 커뮤니티 반응형 구현
  src/components/common/ProfileCard.vue
  src/components/community/CommunityAlarm.vue
  src/components/community/CommunityComment.vue
  src/components/community/CommunityModal.vue
  src/components/community/CommunityMyComment.vue
  src/components/community/CommunityPost.vue
  src/components/community/CommunityPostDetail.vue
  src/components/community/skeleton/CommunityDetailSkel.vue
  src/components/community/skeleton/CommunityPostSkel.vue
  src/components/community/skeleton/ProfileCardSkel.vue
  src/views/community/CommunityDetailView.vue
  src/views/community/CommunityListView.vue
Labels: 🎨 style

#82 ✨ Feat: 모든 소식 카테고리 별 이동
  src/views/newsDetail/CategoryView.vue
Labels: 🛠️ api, 🐛 fix

#85 Feature/server
  src/api/fetchCrawledText.js
  src/components/NewsComponents/NewsComponent8.vue
  src/views/newsDetail/CommunityRecommend.vue
  src/views/newsDetail/NewsDetailView.vue
  src/views/newsDetail/NewsRecommend.vue
Labels: 🛠️ api, ✨ feature, 🐛 fix

#88 🐛 Fix: 스크랩한 뉴스 최신순으로 정렬 및 토스트 메세지 추가
  src/api/community/post.js
  src/views/profile/ProfileNewsView.vue
  src/views/profile/ProfileView.vue
Labels: 🐛 fix, 🎨 style

#90 🐛 Fix: 커뮤니티 페이지에서 다른 사람 프로필 누르면 그 프로필로 이동하도록 라우터 수정
  src/components/community/CommunityPostDetail.vue
Labels: 🐛 fix
